application:
  host: 0.0.0.0
database:
  require_ssl: true

email_client:
  # Value retrieved from Postmark's API documentation
  base_url: "http://danirut.com/"
  # Use the single sender email you authorised on Postmark!
  sender_email: "mail@danirut.com"